### ISSUE TITLE
An error occurred: got an unexpected keyword argument ?

### ISSUE THREAD

**Issue by PYTHON01100100** [Hetari/pyutube#16]
![image](https://github.com/user-attachments/assets/795825c4-588b-422d-ac62-24608e22b5e0)

and download two files video and audio independently not in one file?!  
sol :❗ An error occurred: got an unexpected keyword argument ?

**Comment by Hetari** [comment]
Please update the following libraries:
```bash
pip install --upgrade pytube pytubefix moviepy
```  
After updating, verify that the version of `pytube` is **1.4.12**, and try downloading the video again.

If the error persists, please share with me the YouTube link.

**Comment by PYTHON01100100** [comment]
thanks it works well 100%

**Comment by Hetari** [comment]
> thanks it works well 100%

Don't mention it 👍
