### ISSUE TITLE
unsolicited download

### ISSUE THREAD

**Issue by Veraellyunjie** [Hetari/pyutube#2]
```
> pyutube
🌍  Checking internet connectionresult=<Response [200]>
✅ There is internet connection

[?] Choose the file type you want to download: 
 > Audio
   Video
   Cancel the download

```
downloads `Fast Whoosh Sound Effect - audio.mp3` which wasn't asked for.
I expected pyutube to either prompt for a link or exit saying "provide a link"

---

Also, `result=<Response [200]>` is perhaps superfluous in `🌍  Checking internet connectionresult=<Response [200]>`

**Comment by Hetari** [comment]
It has come to my attention that, during the development phase, a default link was overlooked when testing the tool. I sincerely apologize for this oversight and any inconvenience it may have caused. Rest assured, we are taking steps to ensure that such an occurrence does not happen again in the future.

I really appreciate you taking the time to share your thoughts with me. Thank you so much for your valuable feedback!👍

**Comment by Hetari** [comment]
You can update the `pyutube` CLI by executing the following command:

```bash
pip install --upgrade pyutube
```

Enjoy the updated version of `pyutube`! If you encounter any further issues or have any questions, please don't hesitate to reach out. I would always appreciate your feedback 😊.
