### ISSUE TITLE
resolutions issue

### ISSUE THREAD

**Issue by Veraellyunjie** [Hetari/pyutube#3]
`pyutube youtu.be/cMPnY7EuZvo`
The video has variants up to 480p on youtube.
But pyutube offers also 720p and 1080p:
```
[?] Choose the resolution you want to download: 
   144p
   240p
   360p
   480p
 > 720p
   1080p
   Cancel the download
```
I selected 720p. pyutube downloaded 360p.
I removed the file and run pyutube again, selecting 480p. pyutube downloaded 360p.
I removed the file and run pyutube again, selecting 144p. pyutube downloaded 360p.

Expectations:
* only available resolutions are listed
* in case of mismatch, pyutube exits with an error instead of downloading another resolution
* in case resolution is available, it downloads it instead of 360p

**Comment by Hetari** [comment]
Hi @Veraellyunjie,

I am excited to let you know that your reported issue has been fixed. 🎉
To verify the fix, upgrade `pyutube` by running 
```bash
pip install --upgrade pyutube
```
After that, you can run and use `pyutube`. You should now see only the available resolutions listed for a video. If you have any concerns or encounter any hiccups along the way, please do not hesitate to contact me.

Best regards,
Ebraheem Alhetari
