### ISSUE TITLE
[FEATURE REQUEST] allow downloading by video ID without whole link

### ISSUE THREAD

**Issue by Veraellyunjie** [Hetari/pyutube#4]
`pyutube cMPnY7EuZvo`
allow the above in addition to the below
`pyutube youtu.be/cMPnY7EuZvo`
`pyutube https://youtube.com/watch?v=cMPnY7EuZvo`

**Comment by Hetari** [comment]
Thank you for your feature request! We're happy to inform you that the suggested functionality has been implemented and is now available in the latest `pyutube 1.1.3` version. 🎉

Users can now download videos by directly providing the video ID without needing the full link, try it out by updating the tool
```bash
pip install --upgrade pyutube
```

Thank you for using pyutube!
