### ISSUE TITLE
[FEATURE REQUEST] filename template

### ISSUE THREAD

**Issue by Veraellyunjie** [Hetari/pyutube#5]
pyutube already saves files as `name - resolution.extension`.
A template for it might be `%name% - %resolution%.%ext%` or maybe some other format.
Then more fields: video ID, channel owner, playlist ID etc.

Then one could achieve same filename layout as with certain another popular video downloader:
`%name% [%id%].%ext%`

I personally find video ID in filename very helpful

**Comment by Hetari** [comment]
Based on your input, we've updated the default filename template to include the video ID as requested. The new default template is `%name% - %resolution% _-_%video_id%.%ext%`.

Currently, this is the only available template format in `pyutube`. However, we understand the value of adding fields such as channel owner and playlist ID in the filename template. We'll consider incorporating these options in future updates to provide users with more customization possibilities.

Thank you again.
