### ISSUE TITLE
default path to save video - current dir

### ISSUE THREAD

**Issue by Veraellyunjie** [Hetari/pyutube#6]
```
> cd /tmp
> pyutube --help
...
│      path      [PATH]  Path to save video [default: /tmp]
...
> cd /
> pyutube --help
...
│      path      [PATH]  Path to save video [default: /]
...
```
Different and confusing output.
A user might mistake the dir they are current in for a dir downloads always go to.
It should not print the value of current dir, but say "current directory" or maybe `.`.

```
│      path      [PATH]  Path to save video [default: <current directory>]
```
```
│      path      [PATH]  Path to save video [default: .]
```

**Comment by Hetari** [comment]
Hello again,

Thank you for bringing this to our attention. This change will provide a consistent and clear indication of the default path, regardless of the user's current location in the filesystem.
Your feedback is valuable to us, and we appreciate you taking the time to bring this to our notice. If you have any other suggestions or concerns, please don't hesitate to let us know.

Have a great day 😊

**Comment by Veraellyunjie** [comment]
`default` twice - confusing:
```
│      path      [PATH]  Path to save video [default: <current directory>] [default: /tmp]
```
```
│      path      [PATH]  Path to save video [default: <current directory>] [default: /]
```

**Comment by Hetari** [comment]
Ah, I understand now. The presence of `[default: /tmp]` or `[default: /]` is likely a feature of the `Typer` library, which I use in the `pyutube` CLI. It seems to be part of the library's functionality. I'll temporarily remove the `[default: <current directory>]` indicator and investigate if there's a way to adjust or modify the defaults for `[default: /tmp]` or `[default: /]`.

Thank you.

**Comment by Hetari** [comment]
Hey there,

I just wanted to express my gratitude for your understanding and patience. I've taken the time to address the issue that was causing some confusion about the default path display in the pyutube CLI.

Enhanced Output Representation:
```bash 
url       TEXT    YouTube URL [required]
path      [PATH]  Path to save video [default: current directory>]
```

I truly appreciate your feedback, Cheers!
