### ISSUE TITLE
resolutions issue - episode 2

### ISSUE THREAD

**Issue by Veraellyunjie** [Hetari/pyutube#7]
I am afraid https://github.com/Hetari/pyutube/issues/3 has been fixed only partially.
With release 1.1.2, only 360p is offered, others are not in the list, even though the video on youtube has 144p, 240p and 480p.
```
[?] Choose the resolution you want to download:                                                              
   360p                                                                                                      
 > Cancel the download
```

**Comment by Hetari** [comment]
Could you share the YouTube link with me? I'd like to take a closer look at the video. Thank you!

**Comment by Veraellyunjie** [comment]
the link is the same as in https://github.com/Hetari/pyutube/issues/3
https://youtu.be/cMPnY7EuZvo

**Comment by Hetari** [comment]
I'm happy to tell you that I've successfully fixed the issue, now all available resolutions are properly listed for download. 

I appreciate your patience. If you encounter any further issues or have any questions, please don't hesitate to let me know, make sure to update the `pyutube` to the latest version `1.1.5`.

Thank you for your feedback, enjoy 🎉!
