### ISSUE TITLE
Cancelling the install is an error?

### ISSUE THREAD

**Issue by Ashfmate** [Hetari/pyutube#8]
Bro, when cancelling a video install, it isn't an error, it is normal, fix it lol.
![20240405_17h55m18s_grim](https://github.com/Hetari/pyutube/assets/46440581/6bc0bec7-3a52-4809-a08c-b3479f36d94c)

**Comment by Ashfmate** [comment]
Nvm, just saw the status of the return value, it is 0, the text was red so I thought you were outputting into stderr

**Comment by Hetari** [comment]
Hey Ashfmate, :handshake:

Thanks for your message. I'm glad you noticed that there wasn't an error when canceling the video installation! 😄

In `pyutube`, I've implemented a cancel option to allow users to abort operations if needed. You saw The cancellation message to inform you that the operation was intentionally stopped (with a red color).

If you have any further questions or suggestions for `pyutube`, please don't hesitate to share! Your feedback is invaluable to me. 

Thanks again for using `pyutube`. :smile: 

Best regards,
Ebraheem Alhetari

**Comment by Hetari** [comment]
by the way! I noticed a weird thing in calculating the total size!!!! I will check it later. 

Thanks again for bringing this to my attention.
